# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: All Things Considered
email: mrchief_2000 AT yahoo DOT com
description: > # this means to ignore newlines until "baseurl:"
  All views are my own and I own the right to copy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mrchief.github.io" # the base hostname & protocol for your site
twitter_username: hrusikeshpanda
github_username:  mrchief

# Build settings
markdown: kramdown
